# Name: Chef Master Standalone

Vagrant.configure("2") do |config|

  # Define vagrant box (VM Image)
  config.vm.box = "ubuntu/trusty64"

  # Network configuration 
  config.vm.hostname = "chef-server"
  config.vm.network "private_network", ip: "192.168.30.30"

  # VM configuration
  config.vm.provider "virtualbox" do |vm|
    vm.memory = "1024"
    vm.cpus = "1"
    vm.name = "Chef Server - Stand Alone"
  end

  # That's all folks. 
end
