# Responsible to Install three nodes with Docker to create docker swarm cluster

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    # Create Three virtualbox machines
    (1..3).each do |i|

        config.vm.define "dnode#{i}" do |dnode|

            # Network Configuration
            dnode.vm.hostname = "dnode-#{i}"
            dnode.vm.network "private_network", ip: "192.168.30.8#{i}"

            # VM Configuration
            dnode.vm.provider "virtualbox" do |vbox|
                vbox.memory = "1024"
                vbox.cpus = "1"
                vbox.name = "Docker node #{i}"
            end

            # define the provision
            dnode.vm.provision "chef_solo" do |chef|
                chef.cookbooks_path = "cookbooks"
                chef.add_recipe "docker::install"
            end

        end
    end
end
