---
- hosts: elastic
  user: ec2-user
  become: true

  tasks:
    - name: Installing elasticsearch
      yum:
        name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.rpm

    - name: Installing java8
      yum:
        name: java-1.8.0-openjdk

    - name: Configuring java8
      file:
        path: /etc/alternatives/jre
        src: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64
        state: link
        force: yes
    - file:
        path: /etc/alternatives/java
        src: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
        state: link
        force: yes

    - name: Configuring elasticsearch
      replace:
        dest: /etc/elasticsearch/jvm.options
        regexp: "-Xmx2g"
        replace: "-Xmx720m"

    - replace:
        dest: /etc/elasticsearch/jvm.options
        regexp: "-Xms2g"
        replace: "-Xms720m"

    - shell: chkconfig --add elasticsearch

    - name: Starting elasticsearch
      service:
        name: elasticsearch
        state: started

