# Name: Elasticsearch 2.0 Cluster

Vagrant.configure("2") do |config|

  # Elasticsearch 5.2 + Kibana
  config.vm.define "elasticsearch01" do |elasticsearch01|
    elasticsearch01.vm.box = "centos/7"
    elasticsearch01.vm.hostname = "midgard"
    elasticsearch01.vm.network "private_network", ip: "192.168.40.2"
    elasticsearch01.vm.network "forwarded_port", guest: 9200, host: 9200
    elasticsearch01.vm.network "forwarded_port", guest: 9300, host: 9300

    elasticsearch01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      vb.name = "elasticsearch01"
    end

    config.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "java8"
      chef.add_recipe "elasticsearch::install"
      chef.node_name = "midgard"
   end
  end
end
